/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin.ai'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminBrandsRouteImport } from './routes/_authenticated/admin.brands'
import { Route as AuthenticatedAdminCreativesRouteImport } from './routes/_authenticated/admin.creatives'
import { Route as AuthenticatedAdminFlowRouteImport } from './routes/_authenticated/admin.flow'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated/admin.integrations'
import { Route as AuthenticatedAdminKnowledgeRouteImport } from './routes/_authenticated/admin.knowledge'
import { Route as AuthenticatedAdminLandingRouteImport } from './routes/_authenticated/admin.landing'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSuppliersRouteImport } from './routes/_authenticated/admin.suppliers'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as AuthenticatedAdminExperimentsIndexRouteImport } from './routes/_authenticated/admin.experiments.index'
import { Route as AuthenticatedAdminExperimentsIdRouteImport } from './routes/_authenticated/admin.experiments.$id'
import { Route as AuthenticatedAdminProductsIndexRouteImport } from './routes/_authenticated/admin.products.index'
import { Route as AuthenticatedAdminProductsSlugRouteImport } from './routes/_authenticated/admin.products.$slug'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/admin/ai',
  path: '/admin/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBrandsRoute =
  AuthenticatedAdminBrandsRouteImport.update({
    id: '/admin/brands',
    path: '/admin/brands',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCreativesRoute =
  AuthenticatedAdminCreativesRouteImport.update({
    id: '/admin/creatives',
    path: '/admin/creatives',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFlowRoute = AuthenticatedAdminFlowRouteImport.update({
  id: '/admin/flow',
  path: '/admin/flow',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/admin/integrations',
    path: '/admin/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminKnowledgeRoute =
  AuthenticatedAdminKnowledgeRouteImport.update({
    id: '/admin/knowledge',
    path: '/admin/knowledge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLandingRoute =
  AuthenticatedAdminLandingRouteImport.update({
    id: '/admin/landing',
    path: '/admin/landing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSuppliersRoute =
  AuthenticatedAdminSuppliersRouteImport.update({
    id: '/admin/suppliers',
    path: '/admin/suppliers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminExperimentsIndexRoute =
  AuthenticatedAdminExperimentsIndexRouteImport.update({
    id: '/admin/experiments/',
    path: '/admin/experiments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminExperimentsIdRoute =
  AuthenticatedAdminExperimentsIdRouteImport.update({
    id: '/admin/experiments/$id',
    path: '/admin/experiments/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProductsIndexRoute =
  AuthenticatedAdminProductsIndexRouteImport.update({
    id: '/admin/products/',
    path: '/admin/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProductsSlugRoute =
  AuthenticatedAdminProductsSlugRouteImport.update({
    id: '/admin/products/$slug',
    path: '/admin/products/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/admin/creatives': typeof AuthenticatedAdminCreativesRoute
  '/admin/flow': typeof AuthenticatedAdminFlowRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/admin/landing': typeof AuthenticatedAdminLandingRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/experiments/$id': typeof AuthenticatedAdminExperimentsIdRoute
  '/admin/products/$slug': typeof AuthenticatedAdminProductsSlugRoute
  '/admin/experiments/': typeof AuthenticatedAdminExperimentsIndexRoute
  '/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/admin/creatives': typeof AuthenticatedAdminCreativesRoute
  '/admin/flow': typeof AuthenticatedAdminFlowRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/admin/landing': typeof AuthenticatedAdminLandingRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/experiments/$id': typeof AuthenticatedAdminExperimentsIdRoute
  '/admin/products/$slug': typeof AuthenticatedAdminProductsSlugRoute
  '/admin/experiments': typeof AuthenticatedAdminExperimentsIndexRoute
  '/admin/products': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/brands': typeof AuthenticatedAdminBrandsRoute
  '/_authenticated/admin/creatives': typeof AuthenticatedAdminCreativesRoute
  '/_authenticated/admin/flow': typeof AuthenticatedAdminFlowRoute
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/_authenticated/admin/landing': typeof AuthenticatedAdminLandingRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/experiments/$id': typeof AuthenticatedAdminExperimentsIdRoute
  '/_authenticated/admin/products/$slug': typeof AuthenticatedAdminProductsSlugRoute
  '/_authenticated/admin/experiments/': typeof AuthenticatedAdminExperimentsIndexRoute
  '/_authenticated/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/brands'
    | '/admin/creatives'
    | '/admin/flow'
    | '/admin/integrations'
    | '/admin/knowledge'
    | '/admin/landing'
    | '/admin/settings'
    | '/admin/suppliers'
    | '/api/public/track'
    | '/admin/'
    | '/admin/experiments/$id'
    | '/admin/products/$slug'
    | '/admin/experiments/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/brands'
    | '/admin/creatives'
    | '/admin/flow'
    | '/admin/integrations'
    | '/admin/knowledge'
    | '/admin/landing'
    | '/admin/settings'
    | '/admin/suppliers'
    | '/api/public/track'
    | '/admin'
    | '/admin/experiments/$id'
    | '/admin/products/$slug'
    | '/admin/experiments'
    | '/admin/products'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/brands'
    | '/_authenticated/admin/creatives'
    | '/_authenticated/admin/flow'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/knowledge'
    | '/_authenticated/admin/landing'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/suppliers'
    | '/api/public/track'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/experiments/$id'
    | '/_authenticated/admin/products/$slug'
    | '/_authenticated/admin/experiments/'
    | '/_authenticated/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/admin/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/brands': {
      id: '/_authenticated/admin/brands'
      path: '/admin/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AuthenticatedAdminBrandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/creatives': {
      id: '/_authenticated/admin/creatives'
      path: '/admin/creatives'
      fullPath: '/admin/creatives'
      preLoaderRoute: typeof AuthenticatedAdminCreativesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/flow': {
      id: '/_authenticated/admin/flow'
      path: '/admin/flow'
      fullPath: '/admin/flow'
      preLoaderRoute: typeof AuthenticatedAdminFlowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/knowledge': {
      id: '/_authenticated/admin/knowledge'
      path: '/admin/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/landing': {
      id: '/_authenticated/admin/landing'
      path: '/admin/landing'
      fullPath: '/admin/landing'
      preLoaderRoute: typeof AuthenticatedAdminLandingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/suppliers': {
      id: '/_authenticated/admin/suppliers'
      path: '/admin/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AuthenticatedAdminSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/experiments/': {
      id: '/_authenticated/admin/experiments/'
      path: '/admin/experiments'
      fullPath: '/admin/experiments/'
      preLoaderRoute: typeof AuthenticatedAdminExperimentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/experiments/$id': {
      id: '/_authenticated/admin/experiments/$id'
      path: '/admin/experiments/$id'
      fullPath: '/admin/experiments/$id'
      preLoaderRoute: typeof AuthenticatedAdminExperimentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/products/': {
      id: '/_authenticated/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthenticatedAdminProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/products/$slug': {
      id: '/_authenticated/admin/products/$slug'
      path: '/admin/products/$slug'
      fullPath: '/admin/products/$slug'
      preLoaderRoute: typeof AuthenticatedAdminProductsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminBrandsRoute: typeof AuthenticatedAdminBrandsRoute
  AuthenticatedAdminCreativesRoute: typeof AuthenticatedAdminCreativesRoute
  AuthenticatedAdminFlowRoute: typeof AuthenticatedAdminFlowRoute
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminKnowledgeRoute: typeof AuthenticatedAdminKnowledgeRoute
  AuthenticatedAdminLandingRoute: typeof AuthenticatedAdminLandingRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSuppliersRoute: typeof AuthenticatedAdminSuppliersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminExperimentsIdRoute: typeof AuthenticatedAdminExperimentsIdRoute
  AuthenticatedAdminProductsSlugRoute: typeof AuthenticatedAdminProductsSlugRoute
  AuthenticatedAdminExperimentsIndexRoute: typeof AuthenticatedAdminExperimentsIndexRoute
  AuthenticatedAdminProductsIndexRoute: typeof AuthenticatedAdminProductsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminBrandsRoute: AuthenticatedAdminBrandsRoute,
  AuthenticatedAdminCreativesRoute: AuthenticatedAdminCreativesRoute,
  AuthenticatedAdminFlowRoute: AuthenticatedAdminFlowRoute,
  AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
  AuthenticatedAdminKnowledgeRoute: AuthenticatedAdminKnowledgeRoute,
  AuthenticatedAdminLandingRoute: AuthenticatedAdminLandingRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSuppliersRoute: AuthenticatedAdminSuppliersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminExperimentsIdRoute: AuthenticatedAdminExperimentsIdRoute,
  AuthenticatedAdminProductsSlugRoute: AuthenticatedAdminProductsSlugRoute,
  AuthenticatedAdminExperimentsIndexRoute:
    AuthenticatedAdminExperimentsIndexRoute,
  AuthenticatedAdminProductsIndexRoute: AuthenticatedAdminProductsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
